# Generated by Django 5.0.9 on 2024-09-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogContactPage',
            new_name='ContactPage',
        ),
    ]
