# Generated by Django 5.0.9 on 2024-09-29 07:59

import blog.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blogcontactpage_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('table', 3), ('equation', 4), ('markdown', 5), ('gallery', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Heading'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraph'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Table'}), 4: ('wagtailmath.blocks.MathBlock', (), {'label': 'Equation'}), 5: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'code'}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Gallery title', 'required': True}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Add images to gallery'}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('images', 8)]], {})}, default=blog.blocks.BodyBlock.get_default_value),
        ),
        migrations.AlterField(
            model_name='singlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('table', 3), ('equation', 4), ('markdown', 5), ('gallery', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Heading'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraph'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Table'}), 4: ('wagtailmath.blocks.MathBlock', (), {'label': 'Equation'}), 5: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'code'}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Gallery title', 'required': True}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Add images to gallery'}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('images', 8)]], {})}, default=blog.blocks.BodyBlock.get_default_value),
        ),
    ]
