upstream miicms {
    server djangosvc:8000;
}

server {
    listen 80;

    location /media {
        alias /usr/miicms/media;
        autoindex on;
    }
    
    location /static {
        alias /usr/miicms/static;
        autoindex on;
    }

    location / {
        proxy_pass http://miicms;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

}
